spring:
  application:
    name: calculator

server:
  port: 8083
  error:
    include-message: always

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/